/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 5.0 */
package Compiler;

public interface CompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSTATEMENT = 2;
  public int JJTTYPE = 3;
  public int JJTIFSTMT = 4;
  public int JJTWHILESTMT = 5;
  public int JJTDOWHILESTMT = 6;
  public int JJTFORSTMT = 7;
  public int JJTDECLARESTMT = 8;
  public int JJTASSIGNSTMT = 9;
  public int JJTFORINITSTMT = 10;
  public int JJTBLOCKSTMT = 11;
  public int JJTEXPRESSION = 12;
  public int JJTPOLYNOMIAL = 13;
  public int JJTTERM = 14;
  public int JJTFACTOR = 15;
  public int JJTREADSTMT = 16;
  public int JJTWRITESTMT = 17;


  public String[] jjtNodeName = {
    "start",
    "procedure",
    "Statement",
    "type",
    "IfStmt",
    "WhileStmt",
    "DoWhileStmt",
    "ForStmt",
    "DeclareStmt",
    "AssignStmt",
    "ForInitStmt",
    "BlockStmt",
    "expression",
    "polynomial",
    "term",
    "factor",
    "ReadStmt",
    "WriteStmt",
  };
}
/* JavaCC - OriginalChecksum=94769d4374c8494b04317df54752cb07 (do not edit this line) */
